### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by AlexDarchuk** [AlexDarchuk/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by Olena-Kunovska** [comment]
I am by heritage a Jew, by citizenship a Swiss, and by makeup a human being, and only a human being, without any special attachment to any state or national entity whatsoever.

**Comment by AlexDarchuk** [comment]
Thanks!

**Comment by AlexDarchuk** [comment]
- https://www.facebook.com/AlbertEinstein
- https://www.youtube.com/AlbertEinstein
- https://twitter.com/alberteinstein
- https://instagram.com/alberteinstein
