### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by AlexDarchuk** [AlexDarchuk/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by Olena-Kunovska** [comment]
**Einstein always appeared to have a clear view of the problems of physics and the determination to solve them. He had a strategy of his own and was able to visualize the main stages on the way to his goal. He regarded his major achievements as mere stepping-stones for the next advance.**

**Comment by AlexDarchuk** [comment]
Thanks!
