### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by AlexDarchuk** [AlexDarchuk/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by Olena-Kunovska** [comment]
[LANGUAGES](url)

ENGLISH  GERMAN

[SKILLS](url)

The most important skills of albert einstein were imagination and curiosity . because once a girl asked him what special talent do you have he said i don’t have any special talent i am just curios . also because of his imagination power he was able to discover special relativity , general relativity.

[DISCOVERY](url)

- General theory of relativity
- Special theory of relativity
- Brownian motion
- Photoelectric effect
- EPR paradox
- Equivalence of mass and energy
- Field equations
- Bose - Einstein statistics Bose 
- Einstein condensation

**Comment by AlexDarchuk** [comment]
Thanks!

**Comment by Olena-Kunovska** [comment]
<h4>
                    <a id="user-content-languages" class="anchor" aria-hidden="true" href="#languages"><svg class="octicon octicon-link" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"><path fill-rule="evenodd" d="M7.775 3.275a.75.75 0 001.06 1.06l1.25-1.25a2 2 0 112.83 2.83l-2.5 2.5a2 2 0 01-2.83 0 .75.75 0 00-1.06 1.06 3.5 3.5 0 004.95 0l2.5-2.5a3.5 3.5 0 00-4.95-4.95l-1.25 1.25zm-4.69 9.64a2 2 0 010-2.83l2.5-2.5a2 2 0 012.83 0 .75.75 0 001.06-1.06 3.5 3.5 0 00-4.95 0l-2.5 2.5a3.5 3.5 0 004.95 4.95l1.25-1.25a.75.75 0 00-1.06-1.06l-1.25 1.25a2 2 0 01-2.83 0z"></path></svg></a>LANGUAGES
                  </h4>
                  <p>
                      <g-emoji class="g-emoji" alias="us" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f1fa-1f1f8.png">
                          <img class="emoji" alt="us" height="20" width="20" src="https://github.githubassets.com/images/icons/emoji/unicode/1f1fa-1f1f8.png">
                      </g-emoji> ENGLISH <g-emoji class="g-emoji" alias="ru" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f1e9-1f1ea.png">
                          <img class="emoji" alt="ru" height="20" width="20" src="https://github.githubassets.com/images/icons/emoji/unicode/1f1e9-1f1ea.png"></g-emoji> 
                        GERMANY
                  </p>
                  <h4>
                      <a id="user-content-skills" class="anchor" aria-hidden="true" href="#skills">
                        <svg class="octicon octicon-link" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true">
                          <path fill-rule="evenodd" d="M7.775 3.275a.75.75 0 001.06 1.06l1.25-1.25a2 2 0 112.83 2.83l-2.5 2.5a2 2 0 01-2.83 0 .75.75 0 00-1.06 1.06 3.5 3.5 0 004.95 0l2.5-2.5a3.5 3.5 0 00-4.95-4.95l-1.25 1.25zm-4.69 9.64a2 2 0 010-2.83l2.5-2.5a2 2 0 012.83 0 .75.75 0 001.06-1.06 3.5 3.5 0 00-4.95 0l-2.5 2.5a3.5 3.5 0 004.95 4.95l1.25-1.25a.75.75 0 00-1.06-1.06l-1.25 1.25a2 2 0 01-2.83 0z"></path>
                        </svg>
                      </a>
                    SKILLS
                  </h4>
                      <p>
                        The most important skills of albert einstein were imagination and curiosity . because once a girl asked him what special talent do you have he said i don’t have any special talent i am just curios . also because of his imagination power he was able to discover special relativity , general relativity.
                      </p>
                  <h4>
                      <a id="user-content-character" class="anchor" aria-hidden="true" href="#character"><svg class="octicon octicon-link" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"><path fill-rule="evenodd" d="M7.775 3.275a.75.75 0 001.06 1.06l1.25-1.25a2 2 0 112.83 2.83l-2.5 2.5a2 2 0 01-2.83 0 .75.75 0 00-1.06 1.06 3.5 3.5 0 004.95 0l2.5-2.5a3.5 3.5 0 00-4.95-4.95l-1.25 1.25zm-4.69 9.64a2 2 0 010-2.83l2.5-2.5a2 2 0 012.83 0 .75.75 0 001.06-1.06 3.5 3.5 0 00-4.95 0l-2.5 2.5a3.5 3.5 0 004.95 4.95l1.25-1.25a.75.75 0 00-1.06-1.06l-1.25 1.25a2 2 0 01-2.83 0z"></path>
                        </svg>
                      </a>
                      DISCOVERY
                  </h4>
                  <ul>
                    <li>General theory of relativity</li>
                    <li>Special theory of relativity</li>
                    <li>Brownian motion</li>
                    <li>Photoelectric </li>
                    <li>EPR paradox</li>
                    <li>Equivalence of mass and energy</li>
                    <li>Field equations</li>
                    <li>Bose - Einstein statistics Bose</li>
                    <li>Einstein condensation</li>
                  </ul>
